### ISSUE TITLE
Docker image build on Quay stopped working after 2018-11-18

### ISSUE THREAD

**Issue by njam** [stephenh/mirror#33]
The credentials on Quay to clone the git repo don't work anymore.

> Could not clone git repository: Error cloning git repository (exit status 128) Cloning into '/tmp/build_pack268724775'... Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts. Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. 
https://quay.io/repository/stephenh/mirror/build/74e2adbd-7765-47dd-8b61-9c78602ca1ed

![image](https://user-images.githubusercontent.com/360800/53942598-76efcd80-40bb-11e9-8e09-6732df2e8b6d.png)

@stephenh could you try to delete and re-add the build trigger? I guess it should solve the problem.
-> https://quay.io/repository/stephenh/mirror?tab=builds
![image](https://user-images.githubusercontent.com/360800/53942705-b6b6b500-40bb-11e9-9257-cbd1eae70651.png)

- Trigger: "Trigger for all branches and tags (default)"
- Dockerfile: "/Dockerfile"
- Context: "/"

**Comment by stephenh** [comment]
Thanks for pointing that out; not sure what happened, I may have over-pruned my github account apps/permissions awhile back. Re-added it and it looks fixed. Thanks!
