### ISSUE TITLE
read the host name from ~/.ssh/config

### ISSUE THREAD

**Issue by nathantsoi** [stephenh/mirror#38]
I have ssh configured w/ short names / alias to most of my hosts. It would be awesome if mirror read this config and used these short names to resolve the full name of the host. On the plus side, my ssh config seems to work fine otherwise.

**Comment by stephenh** [comment]
Cool. FWIW I do something similar but via `/etc/hosts` entries, so then the OS's networking stack just automatically knows how to resolve the names (i.e. then both mirror and ssh itself would pick up the aliases). Would that work/be good enough?

**Comment by nathantsoi** [comment]
Ahh, nice. Yep! I'll add an alias in my hosts file.
Nathan
