### ISSUE TITLE
Issues downloading JARs

### ISSUE THREAD

**Issue by ageis** [stephenh/mirror#41]
Cannot resolve repo.joist.ws.

kevin@example:~/dev/mirror$ `wget http://repo.joist.ws/mirror-all.jar`
--2019-09-04 15:18:06--  http://repo.joist.ws/mirror-all.jar
Resolving repo.joist.ws (repo.joist.ws)... failed: Name or service not known.
wget: unable to resolve host address ‘repo.joist.ws’

kevin@example:~/dev/mirror$ `dig @127.0.0.1 repo.joist.ws`

```
; <<>> DiG 9.11.5-P4-5.1+b1-Debian <<>> @127.0.0.1 repo.joist.ws
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 38034
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 5547341fd70235dc (echoed)
;; QUESTION SECTION:
;repo.joist.ws.			IN	A

;; AUTHORITY SECTION:
joist.ws.		716	IN	SOA	ns1.dynadot.com. hostmaster.joist.ws. 1567634111 16384 2048 1048576 2560

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Sep 04 15:18:25 PDT 2019
;; MSG SIZE  rcvd: 132

```

**Comment by stephenh** [comment]
Ah yeah, sorry about that; I was fuddling with my domain/VPS setup and broke that... I'll get things moved over to GitHub releases. Thanks for filing!

**Comment by stephenh** [comment]
Okay, I just uploaded the latest binary to the GitHub Releases pages, v1.3.3, and updated the readme. Should work now but let me know if not. Thanks!
