### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by barrychapman** [stephenh/mirror#45]
You say start from client/server home directory? What directory is this? You also state you can use /bin

It is a bit confusing as to where to place these files and where to run them from

**Comment by stephenh** [comment]
The home directory is a common directory convention on linux, i.e. `/home/stephen` is mine. `~` is a shortcut for this, so `~/bin` means `/home/stephen/bin`, which is on linux/etc. machines where user-downloaded binaries can go.

On mac on this would be `/Users/stephen/` ... and then ... apps? I don't really know.

Basically this means "put the shell script and jar somewhere you can easily run them from".

Happy to accept PRs to make the docs more straightforward.

**Comment by barrychapman** [comment]
Thank you! Got it running, I was just vague on what the definition of home was in the context of this app :) 

Is there a way to daemonize this? Or run as a service?

**Comment by stephenh** [comment]
Nope, daemonizing is a good idea, I just haven't gotten around to it; see #19.
