### ISSUE TITLE
Do not respect .gitignore content

### ISSUE THREAD

**Issue by rleon** [stephenh/mirror#46]
Hi,

Thanks for the project, it works like a charm over large code repository (~3G).

I wonder how can I disable all ",gitignore" files (main one and in subfolders) and sync all files?

Thanks

**Comment by ianvkoeppe** [comment]
Hey there,

Extra includes and excludes patterns can be passed when starting the client, and follow the .gitignore format, e.g.:

It’s always worked for me to just use a wildcard...

`-i ‘*’`

**Comment by rleon** [comment]
The wildcard is great, I'm trying it now.

Thanks

**Comment by stephenh** [comment]
@rleon hey, thanks, glad it's working well for you.

> it works like a charm over large code repository (~3G)

Whew. :-)

> I wonder how can I disable all ",gitignore" files (main one and in subfolders) and sync all files?

I don't have a flag for that currently, just the `-i` / `--includes` to override specific lines from `.gitignore` files. I think a `--sync-all` or something like that would make sense.

Any interest in adding it? I'm not super-actively working on mirror but could probably add it at some point.

**Comment by rleon** [comment]
I don't know Java at all if you need my help with the linux kernel, I'm at your disposal :).

Regarding override, it is a little bit problematic, that file includes a lot of lines and there are .gitignore files in subfolders too.

**Comment by stephenh** [comment]
> I don't know Java at all if you need my help with the linux kernel, I'm at your disposal 

Hehe, sure; this should be pretty easy, I'll try to find some time this weekend.

**Comment by rleon** [comment]
I tried @ianvkoeppe suggestion and it worked perfectly.

Thanks a lot.

**Comment by stephenh** [comment]
Ah nice! I completely missed his comment go by. Thanks Ian! I'll go ahead and add a readme entry about this.
