### ISSUE TITLE
How to mirror two folders in the same machine?

### ISSUE THREAD

**Issue by fenixkim** [stephenh/mirror#5]
Hey, this project is really great!, I would like to know how to "mirror" two folders in the same machine?

**Comment by eliseumds** [comment]
You can use a symlink.

**Comment by stephenh** [comment]
Agreed with @eliseumds, I'm tempted to think that:

```
ln -s /original/directory /copy/directory
```

Would be better/what you want.

On the odd chance for some reason that won't work, starting mirror client with a host of "localhost" should work as well.
