### ISSUE TITLE
About package name

### ISSUE THREAD

**Issue by ccat3z** [stephenh/mirror#51]
This tool is really awesome. I want to submit mirror on [AUR](https://aur.archlinux.org/) (Arch User Repository: a community-driven repository for Arch users), but the name ([aur/mirror](https://aur.archlinux.org/packages/mirror)) is already occupied. Is it ok to use your GitHub ID as a prefix to identify this package (stephenh-mirror)? Can you provide a more suitable and unique name?

**Comment by stephenh** [comment]
Hey, that sounds great! I'd be fine with `stephenh-mirror`. I have no idea what AUR conventions are; just throwing out ideas but maybe `mirror-tool`, `mirror-sync`, `mirror-two-way-sync-tool` :-)

**Comment by ccat3z** [comment]
I submitted [`mirror-sync`](https://aur.archlinux.org/packages/mirror-sync/) pacakge to AUR. By AUR conventions, I also submitted [`mirror-sync-git`](https://aur.archlinux.org/packages/mirror-sync-git/) for latest development version. Arch Linux users can install mirror by `yay -S mirror-sync`. You can add this install guide into README for Arch users if you like.

**Comment by stephenh** [comment]
Great, thanks!
