### ISSUE TITLE
Can we use the diff port instead of '49172'?

### ISSUE THREAD

**Issue by rameshar16** [stephenh/mirror#53]
Can we use the diff port instead of '49172'?

**Comment by stephenh** [comment]
Yes, both the `mirror client` and `mirror server` commands accept a `-p 1234` port argument.

**Comment by rameshar16** [comment]
Thank you @stephenh for your quick response.

**Comment by rameshar16** [comment]
Hi @stephenh,

I have added the "--expose 5001 -p 5001:5001 " to the docker run command, but still, I am seeing the container is running with the default port '49172'.

2020-03-26 08:34:32 INFO  Listening on 0.0.0.0:49172, version unspecified

**Comment by stephenh** [comment]
I do not regularly run the docker command, but the `-p` your passing is being interpretted as a `docker` parameter and not a parameter that is passed to mirror that is running within docker.

If you want `5001` on your local machine to be used, you can leave mirror running on 49182 _within_ docker, and then just map 49172 -> 5001, i.e. something like:

```
docker run --rm --init -it -u $(id -u):$(id -g) -v $(pwd):/data -p 5001:49172 \
  quay.io/stephenh/mirror server
```

Or maybe swap the 5001/49172, not sure what the right order is.

**Comment by rameshar16** [comment]
Thank you @stephenh
