### ISSUE TITLE
logs are not rolling.

### ISSUE THREAD

**Issue by rameshar16** [stephenh/mirror#58]
Hi @stephenh,

Initially, I have tested the bi-direction sync with the fewer files and I was able to view the logs are rolling.
later, I have tested the bi-direction sync with the more files and I am not able to view the rolling logs.

Please help me in fixing the issue.

Thanks and Regards,
Ramesh AR

**Comment by stephenh** [comment]
What does "rolling logs" mean? can you clarify on what "more files" is? Like how many files? And how big is your largest file and how big are the files in total (in MB/GB)?

**Comment by rameshar16** [comment]
Hi @stephenh,

Thank you for your reply.

After a few mins. I am seeing the logs incrementing. The total file size is around 6GB.

Thanks and Regards,
Ramesh AR
