### ISSUE TITLE
exclude file pattern issue

### ISSUE THREAD

**Issue by rameshar16** [stephenh/mirror#59]
Hi @stephenh,

I have given the exclude file pattern as "--exclude='Upload/*'". Here the service is excluding all the files along with the "Upload" dir. 
I want to exclude the file/suddirs of 'Upload' dir and it should sync the 'Upload' dir.

Please help me on fixing the issue.

Thanks and Regards,
Ramesh AR

**Comment by stephenh** [comment]
> I want to exclude the file/suddirs of 'Upload' dir and it should sync the 'Upload' dir.

I don't understand. Can you give an example with concrete file paths? I.e. `Upload/foo/bar.txt` does X and `Upload/zaz/whatever.txt` does Y but you want it to do Z?

**Comment by rameshar16** [comment]
It is working for me after I give the exclude dir pattern as '*/Upload/*'

Thank you @stephenh
