### ISSUE TITLE
Specify log file path?

### ISSUE THREAD

**Issue by barrychapman** [stephenh/mirror#65]
Is it possible to specify a log file path? like have it write to /var/log/mirror instead of my web directory where it could be accessed?

**Comment by stephenh** [comment]
Hi @barrychapman , no that's not currently configurable right now. It's hard-coded here:

https://github.com/stephenh/mirror/blob/9e72dff857d389d6853b535fd85b1122a73c9be6/src/main/java/mirror/LoggingConfig.java#L84

The simplest thing would be to just fork `mirror` and add your own preferred hard-coded path :-) 

But a PR to add a command line flag would be great too.

**Comment by barrychapman** [comment]
> Hi @barrychapman , no that's not currently configurable right now. It's hard-coded here:
> 
> https://github.com/stephenh/mirror/blob/9e72dff857d389d6853b535fd85b1122a73c9be6/src/main/java/mirror/LoggingConfig.java#L84
> 
> The simplest thing would be to just fork `mirror` and add your own preferred hard-coded path :-)
> 
> But a PR to add a command line flag would be great too.

Pull request submitted!

#66

**Comment by barrychapman** [comment]
@stephenh fyi

**Comment by stephenh** [comment]
Included in the latest release.
